#Amortization Schedule

__Scenario__

Samantha is a recent college graduate who has just landed her first job. With her newfound income, she decides it's time to purchase a reliable car to commute to work and run errands. After researching her options, Samantha finds a used car that fits her needs priced at $20,000.

However, Samantha doesn't have enough savings to purchase the car outright. Instead, she decides to take out a loan to finance the purchase. After reviewing her options, she settles on a loan with the following terms:

* Loan Term: 4 years
* APR: 6% compounded monthly


Excited about her new purchase, Samantha is eager to calculate her monthly payments to ensure they fit within her budget. She knows that understanding her financial commitments is crucial to maintaining her financial stability as she embarks on this new chapter in her life.

Question:

1. What will be Samantha's monthly payment for the car loan?

2. After Samantha secures a loan with a term of 4 years and an APR of 6% compounded monthly to purchase a used car priced at $20,000, what would be the breakdown of her monthly payments over the loan term, including the interest and principal portions, as well as the remaining loan balance after each payment?

In [19]:
#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [20]:
# Function to calculate monthly payment
def calculate_monthly_payment(principal, annual_interest_rate, loan_term_years):
    monthly_interest_rate = annual_interest_rate / 12 / 100
    total_payments = loan_term_years * 12
    monthly_payment = (principal * monthly_interest_rate) / (1 - (1 + monthly_interest_rate) ** -total_payments)
    return monthly_payment

# Function to calculate amortization schedule
def calculate_amortization_schedule(principal, annual_interest_rate, loan_term_years):
    monthly_interest_rate = annual_interest_rate / 12 / 100
    total_payments = loan_term_years * 12

    # Calculate monthly payment
    monthly_payment = calculate_monthly_payment(principal, annual_interest_rate, loan_term_years)

    # Initialize lists to store values
    periods = []
    interests = []
    principals = []
    total_payments_list = []
    loan_balance = []

    # Initialize loan balance
    remaining_balance = principal

    # Calculate amortization schedule
    for i in range(1, total_payments + 1):
        interest_payment = remaining_balance * monthly_interest_rate
        principal_payment = monthly_payment - interest_payment
        remaining_balance -= principal_payment

        periods.append(i)
        interests.append(interest_payment)
        principals.append(principal_payment)
        total_payments_list.append(monthly_payment)
        loan_balance.append(remaining_balance)

    # Create DataFrame for amortization schedule
    amortization_schedule = pd.DataFrame({
        "Period": periods,
        "Interest": interests,
        "Principal": principals,
        "Total Payment": total_payments_list,
        "Loan Balance": loan_balance
    })

    return amortization_schedule

# Loan parameters
principal = 20000
annual_interest_rate = 6
loan_term_years = 4

# Calculate monthly payment
monthly_payment = calculate_monthly_payment(principal, annual_interest_rate, loan_term_years)
print(f"Samantha's monthly payment for the car loan: ${monthly_payment:.2f}")

Samantha's monthly payment for the car loan: $469.70

In [21]:
# Calculate amortization schedule
amortization_schedule = calculate_amortization_schedule(principal, annual_interest_rate, loan_term_years)

In [22]:
# Format the columns with 2 decimal places and add a dollar sign
amortization_schedule[['Interest','Principal', 'Total Payment', 'Loan Balance']] = amortization_schedule[['Interest','Principal', 'Total Payment', 'Loan Balance']].applymap('${:.2f}'.format)

In [23]:
amortization_schedule

    Period Interest Principal Total Payment Loan Balance
0        1  $100.00   $369.70       $469.70    $19630.30
1        2   $98.15   $371.55       $469.70    $19258.75
2        3   $96.29   $373.41       $469.70    $18885.34
3        4   $94.43   $375.27       $469.70    $18510.07
4        5   $92.55   $377.15       $469.70    $18132.92
5        6   $90.66   $379.04       $469.70    $17753.88
6        7   $88.77   $380.93       $469.70    $17372.95
7        8   $86.86   $382.84       $469.70    $16990.12
8        9   $84.95   $384.75       $469.70    $16605.37
9       10   $83.03   $386.67       $469.70    $16218.69
10      11   $81.09   $388.61       $469.70    $15830.09
11      12   $79.15   $390.55       $469.70    $15439.54
12      13   $77.20   $392.50       $469.70    $15047.03
13      14   $75.24   $394.47       $469.70    $14652.57
14      15   $73.26   $396.44       $469.70    $14256.13
15      16   $71.28   $398.42       $469.70    $13857.71
16      17   $69.29   $400.41       $469.70    $13457.30
17      18   $67.29   $402.41       $469.70    $13054.88
18      19   $65.27   $404.43       $469.70    $12650.46
19      20   $63.25   $406.45       $469.70    $12244.01
20      21   $61.22   $408.48       $469.70    $11835.53
21      22   $59.18   $410.52       $469.70    $11425.01
22      23   $57.13   $412.58       $469.70    $11012.43
23      24   $55.06   $414.64       $469.70    $10597.79
24      25   $52.99   $416.71       $469.70    $10181.08
25      26   $50.91   $418.80       $469.70     $9762.28
26      27   $48.81   $420.89       $469.70     $9341.40
27      28   $46.71   $422.99       $469.70     $8918.40
28      29   $44.59   $425.11       $469.70     $8493.29
29      30   $42.47   $427.23       $469.70     $8066.06
30      31   $40.33   $429.37       $469.70     $7636.69
31      32   $38.18   $431.52       $469.70     $7205.17
32      33   $36.03   $433.67       $469.70     $6771.50
33      34   $33.86   $435.84       $469.70     $6335.65
34      35   $31.68   $438.02       $469.70     $5897.63
35      36   $29.49   $440.21       $469.70     $5457.42
36      37   $27.29   $442.41       $469.70     $5015.01
37      38   $25.08   $444.63       $469.70     $4570.38
38      39   $22.85   $446.85       $469.70     $4123.53
39      40   $20.62   $449.08       $469.70     $3674.45
40      41   $18.37   $451.33       $469.70     $3223.12
41      42   $16.12   $453.58       $469.70     $2769.54
42      43   $13.85   $455.85       $469.70     $2313.68
43      44   $11.57   $458.13       $469.70     $1855.55
44      45    $9.28   $460.42       $469.70     $1395.13
45      46    $6.98   $462.72       $469.70      $932.40
46      47    $4.66   $465.04       $469.70      $467.36
47      48    $2.34   $467.36       $469.70       $-0.00

These results provide Samantha with valuable information regarding her financial commitments for the car loan, helping her to plan her budget effectively and understand the progression of her loan payments over time.